CREATE SCHEMA IF NOT EXISTS crm_service;
GRANT USAGE ON SCHEMA crm_service TO crm_service_role;
GRANT ALL PRIVILEGES ON SCHEMA crm_service TO crm_flyway_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA crm_service TO crm_service_role;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA crm_service TO crm_service;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA crm_service TO crm_service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm_service GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO crm_service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm_service GRANT USAGE ON SEQUENCES TO crm_service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm_service GRANT EXECUTE ON FUNCTIONS TO crm_service_role;
